### ISSUE TITLE
Excellent boilerplate! Any chance of turning it into an NPM package?

### ISSUE THREAD

**Issue by MichaelHazani** [digitalthrive/Harvest#24]
Out of sheer laziness, more than anything - to let me (and others) be even more lazy by kickstarting a project with "npm harvest" or so instead of looking up the repo every time. Just a thought. Thanks for all your work!

**Comment by ryanbenson** [comment]
Thanks :) I appreciate it!
Were you thinking like a global package or just tossing it up on npm so it's searchable? It's a great idea!

**Comment by MichaelHazani** [comment]
Either way, really. personally I think I'd like to install locally anew, every project. 

It would be great to jumpstart a webapp by "npm harvest (prob taken, so maybe something similar)"-ing it, and also save the extra step of re-associating the GitHub remote links.

**Comment by ryanbenson** [comment]
I've looked into this and thought about it, but I think this is just a lack of my knowledge but how would I go about that? I know I can drop my project up into npmjs.com and publish my package, but wouldn't that just make it available through npm install and npm search? I'm not sure that would allow someone to run `npm harvest` and it gives them the files.

Any suggestions? I appreciate it :)

**Comment by MichaelHazani** [comment]
Not an npm pro myself - but according to the docs it seems like it should
indeed be as simple as adding Harvest to the npm registry. In my experience
there's a 1-to-1 correlation between the way a package appears on the
website and its "npm install " syntax; so I'd assume that's the case. Wish
I could be of more help:)
